// var-spa-vue/src/components/VehicleList.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { Vehicle } from "../interfaces/vehicle";
import VehicleListFilters from "./VehicleListFilters.vue";
import VehicleListItem from "./VehicleListItem.vue";

const props = defineProps<{
  vehicleList: Vehicle[];
}>();

const filterText = ref<string>("");
const unassignedOnly = ref<boolean>(false);
const vehicleListFiltered = ref<Vehicle[]>([]);

function handleFilterTextChanged(newValue: string) {
  filterText.value = newValue;
}
function handleUnassignedOnlyChanged(newValue: boolean) {
  unassignedOnly.value = newValue;
}
function filterVehicles() {
  vehicleListFiltered.value = props.vehicleList  // Start with the complete vehicle list passed via props
    .filter(v => v.driver.includes(filterText.value))  // Apply text filter
    .filter(v => unassignedOnly.value ? !v.driver : true);  // Apply "unassigned only" filter
}

filterVehicles();  // Run initially to populate "vehicleListFiltered"
watch([filterText, unassignedOnly], filterVehicles);  // Afterwards, watch for changes to filter values
</script>

<template>
  <VehicleListFilters
    :filter-text="filterText"
    :unassigned-only="unassignedOnly"
    @filter-text-changed="handleFilterTextChanged"
    @unassigned-only-changed="handleUnassignedOnlyChanged"
  />
  <ul>
    <li v-for="vehicle in vehicleListFiltered" :key="vehicle.id">
      <VehicleListItem :vehicle />
    </li>
  </ul>
</template>

// var-spa-angular/src/app/components/vehicle-list/vehicle-list.component.ts
import { Component, Input, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { Vehicle } from '../../interfaces/vehicle';
import { VehicleListFiltersComponent } from "../vehicle-list-filters/vehicle-list-filters.component";
import { VehicleListItemComponent } from '../vehicle-list-item/vehicle-list-item.component';
import { VehicleListFiltersService } from '../../services/vehicle-list-filters.service';
import { VehicleListFiltersFormValue } from '../../interfaces/vehicle-list-filters-form-value';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-vehicle-list',
  standalone: true,
  imports: [
    VehicleListFiltersComponent,
    VehicleListItemComponent,
  ],
  templateUrl: './vehicle-list.component.html',
  styleUrl: './vehicle-list.component.css'
})
export class VehicleListComponent implements OnInit, OnDestroy {
  @Input() vehicleList: Vehicle[] = [];

  formValueSubscription: Subscription|null = null;
  formValue: VehicleListFiltersFormValue|null = null;
  vehicleListFiltered: Vehicle[] = [];

  constructor(
    private vehicleListFiltersService: VehicleListFiltersService,
  ) {}

  ngOnInit(): void {
    this.vehicleListFiltered = this.vehicleList.concat();

    // Whenever filter values change, re-filter the list of vehicles.
    this.formValueSubscription = this.vehicleListFiltersService.formValue.subscribe((formValue) => {
      this.formValue = formValue;
      this.vehicleListFiltered = this.filterVehicles(this.vehicleList, this.formValue);
    });
  }

  ngOnDestroy(): void {
    if (this.formValueSubscription) {
      this.formValueSubscription.unsubscribe();
    }
  }

  filterVehicles(vehicleList: Vehicle[], formValue: VehicleListFiltersFormValue): Vehicle[] {
    return vehicleList  // Start with the vehicle list passed here
      .filter(v => v.driver.includes(formValue.filterText || ""))  // Apply text filter
      .filter(v => formValue.unassignedOnly ? !v.driver : true);  // Apply "unassigned only" filter
  }
}

<app-vehicle-list-filters></app-vehicle-list-filters>
<ul>
  @for (vehicle of vehicleListFiltered; track vehicle.id) {
    <li>
      <app-vehicle-list-item [vehicle]="vehicle"></app-vehicle-list-item>
    </li>
  }
</ul>
