// var-spa-react/src/components/VehicleListFilters.tsx
interface VehicleListFiltersProps {
  filterText: string;
  setFilterText: any;
  unassignedOnly: boolean;
  setUnassignedOnly: any;
}

export default function VehicleListFilters({
  filterText,
  setFilterText,
  unassignedOnly,
  setUnassignedOnly,
}: VehicleListFiltersProps) {

  return (
    <form>
      <label>
        Driver
        <input
          type="text"
          value={filterText}
          onChange={(e) => setFilterText(e.target.value)}
        />
      </label>
      <label>
        Unassigned
        <input
          type="checkbox"
          checked={unassignedOnly}
          onChange={(e) => setUnassignedOnly(e.target.checked)}
        />
      </label>
    </form>
  );
}

// var-spa-vue/src/components/VehicleListFilters.vue
<script setup lang="ts">
const props = defineProps<{
  filterText: string;
  unassignedOnly: boolean;
}>();

const emit = defineEmits<{
  filterTextChanged: [newValue: string];
  unassignedOnlyChanged: [newValue: boolean];
}>();

function handleFilterTextInput(e: any) {
  emit('filterTextChanged', e.target.value);
}
function handleUnassignedOnlyChange(e: any) {
  emit('unassignedOnlyChanged', e.target.checked);
}
</script>

<template>
  <form>
    <label>
      Driver
      <input
        type="text"
        :value="props.filterText"
        @input="handleFilterTextInput"
      />
    </label>
    <label>
      Unassigned
      <input
        type="checkbox"
        :checked="props.unassignedOnly"
        @change="handleUnassignedOnlyChange"
      />
    </label>
  </form>
</template>
