// var-spa-react/src/components/VehicleDetails.tsx
import { Vehicle } from "../interfaces/vehicle";

export default function VehicleDetails({ vehicleDetails }: {vehicleDetails: Vehicle}) {
  return (
    <dl>
      <dt>ID</dt>
      <dd>{ vehicleDetails.id }</dd>
      <dt>Driver</dt>
      <dd>{ vehicleDetails.driver }</dd>
      <dt>Location</dt>
      <dd>Lat: { vehicleDetails.location.lat }, Long: { vehicleDetails.location.lng }</dd>
      <dt>Heading</dt>
      <dd>{ vehicleDetails.heading }</dd>
      <dt>Speed</dt>
      <dd>{ vehicleDetails.speed }</dd>
    </dl>
  );
}

// var-spa-vue/src/components/VehicleDetails.vue
<script setup lang="ts">
import { Vehicle } from '../interfaces/vehicle';

const props = defineProps<{
  vehicle: Vehicle;
}>();
</script>

<template>
  <dl>
    <dt>ID</dt>
    <dd>{{ props.vehicle.id }}</dd>
    <dt>Driver</dt>
    <dd>{{ props.vehicle.driver }}</dd>
    <dt>Location</dt>
    <dd>Lat: {{ props.vehicle.location.lat }}, Long: {{ props.vehicle.location.lng }}</dd>
    <dt>Heading</dt>
    <dd>{{ props.vehicle.heading }}</dd>
    <dt>Speed</dt>
    <dd>{{ props.vehicle.speed }}</dd>
  </dl>
</template>
