// var-spa-angular/src/app/views/home-view/home-view.component.ts
import { Component, OnInit } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { catchError, Observable } from 'rxjs';
import { Vehicle } from '../../interfaces/vehicle';
import { VehicleService } from '../../services/vehicle.service';
import { VehicleListComponent } from '../../components/vehicle-list/vehicle-list.component';

@Component({
  selector: 'app-home-view',
  standalone: true,
  imports: [
    AsyncPipe,
    VehicleListComponent,
  ],
  templateUrl: './home-view.component.html',
  styleUrl: './home-view.component.css'
})
export class HomeViewComponent implements OnInit {
  vehicleList$!: Observable<Vehicle[]>;
  vehicleListError!: HttpErrorResponse;

  constructor(
    private vehicleService: VehicleService,
  ) {}

  ngOnInit(): void {
    this.vehicleList$ = this.vehicleService.getVehicleList().pipe(
      catchError((error) => {
        this.vehicleListError = error;
        throw error;
      })
    );
  }
}

<div>
  <h1>Home</h1>
  @if (vehicleList$ | async; as vehicleList) {
    <app-vehicle-list [vehicleList]="vehicleList"></app-vehicle-list>
  } @else if (vehicleListError) {
    <span>Unable to fetch vehicle list. Error message: "{{ vehicleListError.message }}"</span>
  } @else {
    <span>Loading...</span>
  }
</div>

// var-spa-vue/src/views/HomeView.vue
<script setup lang="ts">
import { useFetch } from '../composables/fetch';
import { Vehicle } from '../interfaces/vehicle';
import VehicleList from '../components/VehicleList.vue';

const {data: vehicleList, error} = useFetch<Vehicle[]>("http://localhost:9000/assets");
</script>

<template>
  <div>
    <h1>Home</h1>
    <div v-if="error">Unable to fetch vehicle list. Error message: "{{ error.message }}"</div>
    <div v-else-if="vehicleList">
      <VehicleList :vehicle-list="vehicleList" />
    </div>
    <div v-else>Loading vehicle list...</div>
  </div>
</template>
