// var-spa-angular/src/app/components/vehicle-list-item/vehicle-list-item.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Vehicle } from '../../interfaces/vehicle';

@Component({
  selector: 'app-vehicle-list-item',
  standalone: true,
  imports: [
    RouterLink,
  ],
  templateUrl: './vehicle-list-item.component.html',
  styleUrl: './vehicle-list-item.component.css'
})
export class VehicleListItemComponent {
  @Input() vehicle!: Vehicle;
}

@if (vehicle) {
  <div>
    <dl>
      <dt>ID</dt>
      <dd>{{ vehicle.id }}</dd>
      <dt>Driver</dt>
      <dd>{{ vehicle.driver }}</dd>
      <dt>Location</dt>
      <dd>Lat: {{ vehicle.location.lat }}, Long: {{ vehicle.location.lng }}</dd>
      <dt>Heading</dt>
      <dd>{{ vehicle.heading }}</dd>
      <dt>Speed</dt>
      <dd>{{ vehicle.speed }}</dd>
    </dl>  
    <p>
      <a [routerLink]="['/vehicles', vehicle.id]">Details</a>
    </p>
  </div>
}

// var-spa-react/src/components/VehicleListItem.tsx
import { Link } from "react-router-dom";
import { Vehicle } from "../interfaces/vehicle";

export default function VehicleListItem({ vehicle }: {vehicle: Vehicle}) {
  return (
    <div>
      <dl>
        <dt>ID</dt>
        <dd>{ vehicle.id }</dd>
        <dt>Driver</dt>
        <dd>{ vehicle.driver }</dd>
        <dt>Location</dt>
        <dd>Lat: { vehicle.location.lat }, Long: { vehicle.location.lng }</dd>
        <dt>Heading</dt>
        <dd>{ vehicle.heading }</dd>
        <dt>Speed</dt>
        <dd>{ vehicle.speed }</dd>
      </dl>
      <p>
        <Link to={`vehicles/${vehicle.id}`}>Details</Link>
      </p>
    </div>
  );
}
