// var-spa-vue/src/components/VehicleListItem.vue
<script setup lang="ts">
import { Vehicle } from '../interfaces/vehicle';

const props = defineProps<{
  vehicle: Vehicle;
}>();
</script>

<template>
  <div>
    <dl>
      <dt>ID</dt>
      <dd>{{ props.vehicle.id }}</dd>
      <dt>Location</dt>
      <dd>Lat: {{ props.vehicle.location.lat }}, Long: {{ props.vehicle.location.lng }}</dd>
      <dt>Heading</dt>
      <dd>{{ props.vehicle.heading }}</dd>
      <dt>Speed</dt>
      <dd>{{ props.vehicle.speed }}</dd>
    </dl>
  </div>
</template>

// var-spa-react/src/components/VehicleListItem.tsx
import { Link } from "react-router-dom";
import { Vehicle } from "../interfaces/vehicle";

export default function VehicleListItem({ vehicle }: {vehicle: Vehicle}) {
  return (
    <div>
      <dl>
        <dt>ID</dt>
        <dd>{ vehicle.id }</dd>
        <dt>Location</dt>
        <dd>Lat: { vehicle.location.lat }, Long: { vehicle.location.lng }</dd>
        <dt>Heading</dt>
        <dd>{ vehicle.heading }</dd>
        <dt>Speed</dt>
        <dd>{ vehicle.speed }</dd>
      </dl>
      <p>
        <Link to={`vehicles/${vehicle.id}`}>Details</Link>
      </p>
    </div>
  );
}
