// var-spa-angular/src/app/components/vehicle-details/vehicle-details.component.ts
import { Component, Input } from '@angular/core';
import { Vehicle } from '../../interfaces/vehicle';

@Component({
  selector: 'app-vehicle-details',
  standalone: true,
  imports: [],
  templateUrl: './vehicle-details.component.html',
  styleUrl: './vehicle-details.component.css'
})
export class VehicleDetailsComponent {
  @Input() vehicleDetails!: Vehicle;
}

<dl>
  <dt>ID</dt>
  <dd>{{ vehicleDetails.id }}</dd>
  <dt>Driver</dt>
  <dd>{{ vehicleDetails.driver }}</dd>
  <dt>Location</dt>
  <dd>Lat: {{ vehicleDetails.location.lat }}, Long: {{ vehicleDetails.location.lng }}</dd>
  <dt>Heading</dt>
  <dd>{{ vehicleDetails.heading }}</dd>
  <dt>Speed</dt>
  <dd>{{ vehicleDetails.speed }}</dd>
</dl>

// var-spa-react/src/components/VehicleDetails.tsx
import { Vehicle } from "../interfaces/vehicle";

export default function VehicleDetails({ vehicleDetails }: {vehicleDetails: Vehicle}) {
  return (
    <dl>
      <dt>ID</dt>
      <dd>{ vehicleDetails.id }</dd>
      <dt>Driver</dt>
      <dd>{ vehicleDetails.driver }</dd>
      <dt>Location</dt>
      <dd>Lat: { vehicleDetails.location.lat }, Long: { vehicleDetails.location.lng }</dd>
      <dt>Heading</dt>
      <dd>{ vehicleDetails.heading }</dd>
      <dt>Speed</dt>
      <dd>{ vehicleDetails.speed }</dd>
    </dl>
  );
}
